name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
        env:
          CI_STATUS: ${{ job.status }}
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: generate_and_push
        run: make generate_and_push
      - name: deploy
        run: make deploy

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check code formatting
        run: make format-check
        env:
          CI_STATUS: ${{ job.status }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: make lint
        env:
          CI_STATUS: ${{ job.status }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: make test
        env:
          CI_STATUS: ${{ job.status }}

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: make install
        env:
          CI_STATUS: ${{ job.status }}

  badges:
    runs-on: ubuntu-latest
    steps:
      - name: Format Badge
        run: echo "![Format](https://img.shields.io/badge/format-passing-brightgreen)"
      - name: Lint Badge
        run: echo "![Lint](https://img.shields.io/badge/lint-passing-brightgreen)"
      - name: Test Badge
        run: echo "![Test](https://img.shields.io/badge/test-passing-brightgreen)"
      - name: Install Badge
        run: echo "![Install](https://img.shields.io/badge/install-passing-brightgreen)"